# @file python3check.yml
---
name: Python3 check

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simple hello world
        run: echo "Hello World"
  python3-pywbem-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install latest pywbem from pip
      run: |
        sudo apt-get install -qq -yy python3-pip
        pip3 install pywbem
    - name: Set environment PYTHONPATH
      run: |
        export PYTHONPATH=/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages:${PYTHONPATH}
    - name: Verify python sys.path
      run: (echo "import sys"; echo "print(', '.join(sys.path))") | python
    - name: Launch script with --help
      run: |
        ./check_esxi_hardware.py --help
