# @file python3check.yml
---
name: Python3 check

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  python3-pywbem-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install latest pywbem from pip
      run: |
        sudo apt-get install -qq -yy python3 python3-pip
        pip3 install pywbem
    - name: Verify python sys.path
      run: (echo "import sys"; echo "print(', '.join(sys.path))") | python3
    - name: Launch script with --help
      run: |
        ./check_esxi_hardware.py --help
